           <ul class="pager">
               <li><a href="#">Protected by: <span class="glyphicon  glyphicon-cloud"></span> .Sky</a></li>
           </ul>
        </div>
<!--Always finish the last div here to stay with the same color of the upper row-->
        <script src="<?php echo $_config['SITE']; ?>public/js/jquery.min.js"></script>
        <script src="<?php echo $_config['SITE']; ?>public/js/jquery.pageslide.min.js"></script>
        <script src="<?php echo $_config['SITE']; ?>public/js/bootstrap.min.js"></script>
    </body>
</html>