     <div class='row' style='background-color: #00526e; padding-top: 10px;'>       
            <div class="container">
                <!--Social media-->
                <div class='col-sm-6 col-md-3'>
                    <div class="">
                        <div class="panel-body">
                            <center>
                                <img src="http://www.startupwebtraining.com/wp-content/uploads/2013/06/117990-matte-blue-and-white-square-icon-social-media-logos-facebook-logo.png"  width="64px"/>
                                <img src="http://www.startupwebtraining.com/wp-content/uploads/2013/06/118062-matte-blue-and-white-square-icon-social-media-logos-twitter.png"  width="64px"/>
                            </center>
                        </div>
                    </div>
                </div>
                <!--Finish Social media-->

            </div>

            <ul class="pager">
               <li><a href="#">Protected by: <span class="glyphicon  glyphicon-cloud"></span> .Sky</a></li>
           </ul>
        </div>
<!--Always finish the last div here to stay with the same color of the upper row-->
        <script src="<?php echo $_config['SITE']; ?>public/js/jquery.min.js"></script>
        <script src="<?php echo $_config['SITE']; ?>public/js/bootstrap.min.js"></script>
        <script src="<?php echo $_config['SITE']; ?>public/js/jquery.pajinate.min.js"></script>
        <script src="<?php echo $_config['SITE']; ?>public/js/app.js"></script>
        
    </body>
</html>