<!doctype html>
<html lang="pt-br">
    <head>
        <title>Hair PHP</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <!--  The jquery.pageslide.css stylesheet has the class that you'll need on your page -->
        <link rel="stylesheet" type="text/css" href="<?php echo $_config['SITE']; ?>public/css/jquery.pageslide.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $_config['SITE']; ?>public/css/bootswatch.min.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $_config['SITE']; ?>public/css/style.css" />
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle pull-left" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Style no cabelo</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Link</a></li>
                    <li><a href="#">Link</a></li>
                </ul>
            </div>
        </nav>
        <?php $this->activeLink('index'); ?>