<!doctype html>
<html lang="pt-br">
    <head>

        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <!--  The jquery.pageslide.css stylesheet has the class that you'll need on your page -->
        <link rel="stylesheet" type="text/css" href="<?php echo $_config['SITE']; ?>public/css/jquery.pageslide.css" />
       <link rel="stylesheet" type="text/css" href="<?php echo $_config['SITE']; ?>public/css/bootswatch.min.css" /> 
        <!-- <link rel="stylesheet" type="text/css" href="http://getbootstrap.com/dist/css/bootstrap.min.css" />-->
        <link rel="stylesheet" type="text/css" href="<?php echo $_config['SITE']; ?>public/css/style.css" />
        
        <link rel="shortcut icon" href="<?php echo $_config['SITE']; ?>public/img/favicon.ico" />
        <title>Hair PHP</title>
    </head>
    <body>