<!--Banner's top-->
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src='http://retaildesignblog.net/wp-content/uploads/2012/05/Mahash-Natural-Hair-Spa-by-Reis-Design-Moscow.jpg' alt="Teste">
                <div class="carousel-caption opaco">
                    This is a test
                </div>
            </div>
            <div class="item">
                <img src='http://retaildesignblog.net/wp-content/uploads/2012/05/Mahash-Natural-Hair-Spa-by-Reis-Design-Moscow.jpg' alt="Teste">
                <div class="carousel-caption opaco">
                    This is a test
                </div>
            </div>
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
