<!--Banner's top-->
<div class='row'>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src='http://retaildesignblog.net/wp-content/uploads/2012/05/Mahash-Natural-Hair-Spa-by-Reis-Design-Moscow.jpg' alt="Teste">
                <div class="carousel-caption opaco">
                    This is a test
                </div>
            </div>
            <div class="item">
                <img src='http://retaildesignblog.net/wp-content/uploads/2012/05/Mahash-Natural-Hair-Spa-by-Reis-Design-Moscow.jpg' alt="Teste">
                <div class="carousel-caption opaco">
                    This is a test
                </div>
            </div>
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
</div>

<!--Our services-->
<div class='row'>
    <div class='container'>
        <h3><b>Nossos serviços</b></h3>
        <div class="row">
            <!--Quadrinho 1-->
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src='http://static.blogo.it/dasmariasblog/7/73d/Imagem14-586x402.png' data-src="holder.js/300x200" alt="...">
                    <div class="caption">
                        <h3>Penteado</h3>
                        <p>Trabalhamos com diversos tipos de penteados, babyliss e etc.</p>
                        <p><a href="#" class="btn btn-info" role="button">Saiba mais</a> </p>
                    </div>
                </div>
            </div>
            <!--Quadrinho 2-->
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src='http://beleza.culturamix.com/blog/wp-content/gallery/cabelo-com-corte-quimico-1/cabelo-com-corte-quimico-2.jpg' data-src="holder.js/300x200" alt="...">
                    <div class="caption">
                        <h3>Quimica em geral</h3>
                        <p>Temos especialistas em quimicas em geral incluindo também tratamento.</p>
                        <p><a href="#" class="btn btn-info" role="button">Saiba mais</a> </p>
                    </div>
                </div>
            </div>
            <!--Quadrinho 1-->
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src='http://urie.files.wordpress.com/2008/07/trey-songz-c-340x240.jpg' data-src="holder.js/300x200" alt="...">
                    <div class="caption">
                        <h3>Cortes M/F</h3>
                        <p>Com profissionais seu cabelo sempre esta em boas mãos, cortes M/F e infantil.</p>
                        <p><a href="#" class="btn btn-info" role="button">Saiba mais</a> </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class='row' style='background-color: #00526e; padding-top: 10px;'>
    <div class='container'>
        <!--Pic of the instructure-->
        <div class='col-sm-6 col-md-8'>
            <div class='thumbnail'>
                <h3 class='text-primary'><b>Conheça o conforto de nossas instalações</b></h3>
                <a href='#'>
                    <img class='img-thumbnail' src='http://www.galwan.com.br/nelson-prest/inc/img/lazer/salao-de-beleza.jpg' alt="..."/>
                    <div class="carousel-caption">
                        Conforto qualidade e preço acessivel somente aqui.
                    </div>
                </a>
            </div>
        </div>
        <!--Finish of pic of the instructure-->
        <!--Marketing to prices-->
        <div class='col-sm-6 col-md-4'>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span class='glyphicon glyphicon-usd h1'></span><b class='h1'> Preços </b>
                </div>
                <div class="panel-body">
                    Confira nossa tabela de preços e não fique fora dessa.
                    <!--Tabs-->
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#masculino" data-toggle="tab">Masc.</a></li>
                        <li><a href="#feminino" data-toggle="tab">Fem.</a></li>
                        <li><a href="#infantil" data-toggle="tab">Infantil</a></li>
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div class="tab-pane active" id="masculino"><?php include 'precosMasc.phtml'; ?></div>
                        <div class="tab-pane" id="feminino"><?php include 'precosFem.phtml'; ?></div>
                        <div class="tab-pane" id="infantil"><?php include 'precosInf.phtml'; ?></div>
                    </div>
                    <a class="center-block btn btn-primary" ><span class="glyphicon glyphicon-plus-sign white "></span>  Veja mais</a>
                    <!--Finish Tabs-->
                </div>
            </div>
        </div>
        <!--Finish Marketing to prices-->
    </div>
</div>
<!--Finish another row-->
<!--Begin row media marketing-->
<div class='row' style='background-color: #00526e; padding-top: 10px;'>
    <div class="container">
        <!--Social media-->
        <div class='col-sm-6 col-md-4'>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span class='glyphicon glyphicon-thumbs-up'></span> Redes sociais
                </div>
                <div class="panel-body">
                    Facebook, Twitter e etc.
                </div>
            </div>
        </div>
        <!--Finish Social media-->
        <!--Senssational Equip-->
        <div class='col-sm-6 col-md-4'>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span class='glyphicon glyphicon-user white'></span> Equipe sensacional!
                </div>
                <div class="panel-body">
                    Uma equipe altamente treinada.
                </div>
            </div>
        </div>
        <!--Finish Senssational Equip-->
    </div>
