<!--Banner's top-->
<div class='row'>
    <?php include 'banner.phtml'; ?>
</div>


<div class='row' style='background-color: #00526e; padding-top: 10px;'>
    <div class='container'>
        <!--Pic of the instructure-->
        <?php include 'top.phtml'; ?>
        <!--Finish Marketing to prices-->
    </div>
</div>
<!--Finish another row-->

<!--Our services-->
<div class='row'>
    <?php include 'mid.phtml'; ?>
</div>

<!--Begin row media marketing-->

