<!doctype html>
<html lang="en">
    <head>
        <title>jQuery PageSlide Demo</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <!--  The jquery.pageslide.css stylesheet has the class that you'll need on your page -->
        <link rel="stylesheet" type="text/css" href="<?php echo $_config['SITE']; ?>public/css/jquery.pageslide.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $_config['SITE']; ?>public/css/bootswatch.min.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $_config['SITE']; ?>public/css/bootswatch.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $_config['SITE']; ?>public/css/style.css" />
    </head>
    <body>

        <div class='nav navbar-fixed-top' id="content">
            <h1><a class="open" href="#nav">Menu</a>PageSlide Responsive Demo</h1>
            <ul id="nav">
                <li><a href="">Menu Item 1</a></li>
                <li><a href="">Menu Item 2</a></li>
                <li><a href="">Menu Item 3</a></li>
                <li><a href="">Menu Item 4</a></li>
                <li><a href="">Menu Item 5</a></li>
            </ul>
            <div class="copy">
                <p>If you've ever used the <a href="http://m.facebook.com">mobile version of Facebook</a>, or <a href="http://www.path.com">Path</a>, then you've probably seen something akin to PageSlide in action.</p>
                <p>In this example, resizing the browser to a smaller window (less than or equal to an iPhone's landscape view) will collapse and hide the faux menu nav above. Clicking on the menu icon will then trigger PageSlide to open.</a>
            </div>
        </div>
        <script src="<?php echo $_config['SITE']; ?>public/js/jquery-1.7.1.min.js"></script>
        <script src="<?php echo $_config['SITE']; ?>public/js/jquery.pageslide.min.js"></script>
        <script>
            $(".open").pageslide();
        </script>
    </body>
</html>
