<div class='container'>
        <h3><b>Nossos serviços</b></h3>
        <div class="row">
            <!--Quadrinho 1-->
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src='http://static.blogo.it/dasmariasblog/7/73d/Imagem14-586x402.png' data-src="holder.js/300x200" alt="...">
                    <div class="caption">
                        <h3>Penteado</h3>
                        <p>Trabalhamos com diversos tipos de penteados, babyliss e etc.</p>
                        <p><a href="#" class="btn btn-info" role="button">Saiba mais</a> </p>
                    </div>
                </div>
            </div>
            <!--Quadrinho 2-->
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src='http://beleza.culturamix.com/blog/wp-content/gallery/cabelo-com-corte-quimico-1/cabelo-com-corte-quimico-2.jpg' data-src="holder.js/300x200" alt="...">
                    <div class="caption">
                        <h3>Quimica em geral</h3>
                        <p>Temos especialistas em quimicas em geral incluindo também tratamento.</p>
                        <p><a href="#" class="btn btn-info" role="button">Saiba mais</a> </p>
                    </div>
                </div>
            </div>
            <!--Quadrinho 1-->
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src='http://urie.files.wordpress.com/2008/07/trey-songz-c-340x240.jpg' data-src="holder.js/300x200" alt="...">
                    <div class="caption">
                        <h3>Cortes M/F</h3>
                        <p>Com profissionais seu cabelo sempre esta em boas mãos, cortes M/F e infantil.</p>
                        <p><a href="#" class="btn btn-info" role="button">Saiba mais</a> </p>
                    </div>
                </div>
            </div>

        </div>
    </div>