<div class="panel panel-default">
    <!-- Table -->
    <table class="table">
        <tr>
            <td><b>Tamanho de cabelo</b></td>
            <td><b>Valor</b></td>
        </tr>
        <tr>
            <td><h3>Cabelo Longo</h3></td>
            <td><h3><div class="label label-danger">R$ 45,00</div></h3></td>
        </tr>
        <tr>
            <td><h3>Cabelo Médio</h3></td>
            <td><h3><div class="label label-danger">R$ 30,00</div></h3></td>
        </tr>
        <tr>
            <td><h3>Cabelo Curto</h3></td>
            <td><h3><div class="label label-danger">R$ 20,00</div></h3></td>
        </tr>

    </table>
</div>