
<!--Pic of the instructure-->
<div class='col-sm-6 col-md-8'>
    <div class='thumbnail'>
        <h3 class='text-primary'><b>Conheça o conforto de nossas instalações</b></h3>
        <a href='#'>
            <img class='img-thumbnail thumbnail-top' src='http://www.galwan.com.br/nelson-prest/inc/img/lazer/salao-de-beleza.jpg' alt="..."/>
            <div class="carousel-caption">
                Conforto qualidade e preço acessivel somente aqui.
            </div>
        </a>
    </div>
</div>
<!--Finish of pic of the instructure-->
<!--Marketing to prices-->
<div class='col-sm-6 col-md-4'>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <b class='h1'> Produtos </b>
        </div>
        <div class="panel-body">
            <p>Confira nossa tabela de preços e não fique fora dessa.</p>
            
            <div class="panel panel-default">
                <center>
                    <img src="http://mystylebell.com/wp-content/uploads/2010/04/Lanza.jpg" width="100%"/>
                </center>
            </div>
            <p><h4>Trabalhamos com produtos excelentes com ótimo conceito de mercado profissional</h4></p>
            <a class="center-block btn btn-primary" href="/hairphp/"><span class="glyphicon glyphicon-plus-sign white "></span>  Veja mais</a>
            <!--Finish Tabs-->
        </div>
    </div>
</div>
<!--Finish Marketing to prices-->
