<div class="container">
    <div class="col-lg-9 col-lg-offset-1 well">
        <h1>Adicionar cliente</h1>
        <form class="form-horizontal container" role="form" method="POST">
            <!--            Nome-->
            <div class="form-group">
                <label for="nome" class="col-sm-2 control-label"><h4>Nome</h4></label>
                <div class="col-sm-5">
                    <input type="text" name="nome" class="form-control input-lg" id="nome" placeholder="Nome">
                </div>
            </div>
        </form>
    </div>
</div>