<div class='row'>
    <div class=" " id="">
        <p><h2>Lista de clientes</h2></p>
        <div class="col-md-3">
            <div class="input-group input-group-lg">
                <input type="text" class="form-control input-search col-md-3" alt="lista-clientes" placeholder="Buscar clientes" />
                <span class="input-group-btn">
                    <button class="btn btn-default" id="clear" type="button"><span class="glyphicon glyphicon-remove-sign"></span></button>
                </span>
            </div>
        </div>
        <br/>

        <div class="row">
            <a class="btn btn-default pull-right" href="<?php echo $_config['SITE'] . $_SESSION['nivel'] . '/funcionario/action/new' ?>"><span class="glyphicon glyphicon-plus-sign"></span></a>
        </div>

        <div id="paging_container">
            <table class="table table-bordered lista-clientes" style="">
                <thead>
                    <tr>
                        <th class="col-lg-1 col-md-1 col-sm-1 col-xs-1">#</th>
                        <th>Nome</th>
                        <th>Usuário</th>
                        <th class="col-lg-1 col-md-1 col-sm-1 col-xs-1">RG</th>
                        <th class="col-lg-1 col-md-1 col-sm-1 col-xs-1"><center>Ativo</center></th>
                        <th class="col-lg-2 col-md-2 col-sm-2 col-xs-2">Opções</th>
                    </tr>
                </thead>
                <tbody id="tbody"></tbody>
                <tbody id="">
                    <?php
                    foreach ($view_linha as $linha => $valor) {
                        echo "<tr class='alt_content'>",
                        "<td>" . $valor['id'] . "</td>",
                        "<td>" . $valor['nome'] . "</td>",
                        "<td>" . $valor['user'] . "</td>",
                        "<td>" . $valor['rg'] . "</td>",
                        "<td><center>";
                        if($valor['ativo'] == 1){
                            echo "<spam class='glyphicon glyphicon-ok'></spam>";
                        }else{
                            echo "<spam class='glyphicon glyphicon-remove'></spam>";
                        }
                        echo
                        "</center></td>",
                        "<td>"
                                . "<a class=' btn btn-sm btn-success' href='{$_config['SITE']}admin/funcionario/action/edit/id/{$valor['id']}'><span class='glyphicon glyphicon-pencil'></span></a> "
                                . "<a class=' btn btn-sm btn-danger' href='{$_config['SITE']}admin/funcionario/action/delete/id/{$valor['id']}'><span class='glyphicon glyphicon-minus'></span></a> "
                                
                        . "</td>",
                        "</tr>";
                    }
                    ?>
                </tbody>
            </table>

            <div class="alt_page_navigation pager" style="">
            </div>


        </div>
    </div>
</div>