<!--Containers-->

<div class='row'>

    <div class=" " id="">
        <p><h2>Lista de Funcionários</h2></p>
        <div class="row">
            <input type="text" class="input-search col-md-3" alt="lista-clientes" placeholder="Buscar nesta lista" />
        </div>
        <div class="row">
            <a class="btn btn-default pull-right" href="<?php echo $_config['SITE'].$_SESSION['nivel'].'/cliente/add/novo' ?>"><span class="glyphicon glyphicon-plus-sign"></span></a>
        </div>
        <table class="table table-bordered lista-clientes" style="">
            <thead>
                <tr>
                    <th class="col-lg-1 col-md-1 col-sm-1 col-xs-1">#</th>
                    <th>Nome</th>
                    <th>Usuário</th>
                    <th class="col-lg-1 col-md-1 col-sm-1 col-xs-1">Ativo</th>
                    <th class="col-lg-2 col-md-2 col-sm-2 col-xs-2">Opções</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Ernandes</td>
                    <td>endsalone</td>
                    <td class="col-lg-1 col-md-1 col-sm-1 col-xs-1">sim</td>
                    <td>Opções</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Diones</td>
                    <td>di</td>
                    <td class="col-lg-1 col-md-1 col-sm-1 col-xs-1">não</td>
                    <td>Opções</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Neuci</td>
                    <td>neuci</td>
                    <td class="col-lg-1 col-md-1 col-sm-1 col-xs-1">sim</td>
                    <td>Opções</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Enardes</td>
                    <td>nardes</td>
                    <td class="col-lg-1 col-md-1 col-sm-1 col-xs-1">sim</td>
                    <td>Opções</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>