<?php //include 'views/index/banner.phtml';      ?>
<div class="row" style="margin-top: 135px;" >
    <div class="well col-md-5 col-md-offset-4" >

        <h2 class="well">Acesso exclusivo</h2>
        <form class="form-signin" method="POST" action="">
            <div class="input-group">
                <span class="input-group-addon "><i class="glyphicon glyphicon-user"></i></span>
                <input type="text" name="user" class="form-control input-lg" placeholder="Usuário" required="" autofocus="">
            </div>
            <div class="input-group">
                <span class="input-group-addon "><i class="glyphicon glyphicon-sound-dolby"></i></span>
                <input type="password" name="password" class="form-control input-lg" placeholder="Senha" required="">
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
            <?php
            if (isset($view_error))
                include 'error.phtml';
            ?>
        </form> 

    </div>   
</div>